const FESTIVALS_DATA = [
  {
    id: 'atx-music-001',
    title: 'Austin City Limits Music Festival',
    category: 'Music',
    city: 'Austin',
    state: 'Texas',
    stateCode: 'TX',
    date: '2026-10-02',
    endDate: '2026-10-11',
    description: 'Two weekends of world-class music across multiple stages in Zilker Park. One of the premier music festivals in the country, ACL features hundreds of artists across all genres.',
    tags: ['music', 'outdoor', 'family', 'multi-day'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Paid',
    organizer: 'C3 Presents',
    vendorOpportunities: true,
    emoji: '🎵'
  },
  {
    id: 'atx-food-002',
    title: 'Austin Food & Wine Festival',
    category: 'Food',
    city: 'Austin',
    state: 'Texas',
    stateCode: 'TX',
    date: '2026-04-24',
    endDate: '2026-04-26',
    description: 'A weekend celebration of food, wine, and the Texas culinary scene. Featuring top chefs, tastings, demos, and the legendary Wild Game Cook-Off.',
    tags: ['food', 'wine', 'outdoor', 'culinary'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Paid',
    organizer: 'Austin Food & Wine Alliance',
    vendorOpportunities: false,
    emoji: '🍷'
  },
  {
    id: 'nola-music-001',
    title: 'New Orleans Jazz & Heritage Festival',
    category: 'Music',
    city: 'New Orleans',
    state: 'Louisiana',
    stateCode: 'LA',
    date: '2026-04-24',
    endDate: '2026-05-03',
    description: 'The legendary Jazz Fest brings together the greatest traditions in music and culture from New Orleans and around the world. Gospel, blues, Cajun, zydeco, jazz, R&B, and more.',
    tags: ['jazz', 'music', 'heritage', 'food', 'outdoor'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Paid',
    organizer: 'Foundation for the Preservation of Jazz',
    vendorOpportunities: true,
    emoji: '🎷'
  },
  {
    id: 'nola-cultural-001',
    title: 'French Quarter Festival',
    category: 'Cultural',
    city: 'New Orleans',
    state: 'Louisiana',
    stateCode: 'LA',
    date: '2026-04-02',
    endDate: '2026-04-05',
    description: 'The world\'s largest free jazz festival, held in the heart of the French Quarter. Featuring hundreds of local musicians, cuisine from top restaurants, and authentic New Orleans culture.',
    tags: ['cultural', 'music', 'food', 'free', 'outdoor'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'French Quarter Festivals Inc.',
    vendorOpportunities: true,
    emoji: '🎺'
  },
  {
    id: 'chi-food-001',
    title: 'Chicago Taste of Chicago',
    category: 'Food',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    date: '2026-07-08',
    endDate: '2026-07-12',
    description: 'The world\'s largest food festival returns to Grant Park. Sample signature dishes from Chicago\'s best restaurants alongside live entertainment and stunning lakefront views.',
    tags: ['food', 'family', 'outdoor', 'free'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Free',
    organizer: 'Chicago Department of Cultural Affairs',
    vendorOpportunities: true,
    emoji: '🍕'
  },
  {
    id: 'chi-art-001',
    title: 'Chicago Art Week',
    category: 'Art',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    date: '2026-09-11',
    endDate: '2026-09-13',
    description: 'A citywide celebration of contemporary art spanning galleries, museums, studios, and public spaces. Art lovers from around the world converge on Chicago for this must-attend cultural event.',
    tags: ['art', 'contemporary', 'galleries', 'culture'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'Chicago Arts Council',
    vendorOpportunities: false,
    emoji: '🎨'
  },
  {
    id: 'atl-cultural-001',
    title: 'Atlanta Caribbean Carnival',
    category: 'Cultural',
    city: 'Atlanta',
    state: 'Georgia',
    stateCode: 'GA',
    date: '2026-08-01',
    endDate: '2026-08-02',
    description: 'A vibrant celebration of Caribbean culture with colorful costume parades, live soca and reggae music, traditional food, and a festive atmosphere for the whole family.',
    tags: ['cultural', 'caribbean', 'music', 'parade', 'family'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'Atlanta Caribbean Alliance',
    vendorOpportunities: true,
    emoji: '🌴'
  },
  {
    id: 'atl-food-001',
    title: 'Atlanta Food & Wine Festival',
    category: 'Food',
    city: 'Atlanta',
    state: 'Georgia',
    stateCode: 'GA',
    date: '2026-05-28',
    endDate: '2026-05-31',
    description: 'A four-day culinary event celebrating the South\'s diverse food traditions. Tasting tents, cooking demos, and intimate experiences with the South\'s most celebrated chefs.',
    tags: ['food', 'southern', 'wine', 'culinary'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Paid',
    organizer: 'Atlanta Food & Wine LLC',
    vendorOpportunities: false,
    emoji: '🍑'
  },
  {
    id: 'pdx-music-001',
    title: 'Portland MusicFest',
    category: 'Music',
    city: 'Portland',
    state: 'Oregon',
    stateCode: 'OR',
    date: '2026-08-14',
    endDate: '2026-08-16',
    description: 'Portland\'s premier outdoor music festival showcasing indie, folk, alternative, and electronic artists across three stages along the waterfront.',
    tags: ['music', 'indie', 'outdoor', 'waterfront'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Portland Live Events',
    vendorOpportunities: true,
    emoji: '🎸'
  },
  {
    id: 'pdx-art-001',
    title: 'Last Thursday on Alberta',
    category: 'Art',
    city: 'Portland',
    state: 'Oregon',
    stateCode: 'OR',
    date: '2026-06-25',
    endDate: '2026-06-25',
    description: 'Portland\'s beloved monthly art walk on Alberta Street, featuring local artists, performers, food carts, live music, and community celebration on the last Thursday of each month.',
    tags: ['art', 'community', 'free', 'local', 'recurring'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'Alberta Arts District',
    vendorOpportunities: true,
    emoji: '🖼️'
  },
  {
    id: 'pdx-wellness-001',
    title: 'Portland Wellness Festival',
    category: 'Wellness',
    city: 'Portland',
    state: 'Oregon',
    stateCode: 'OR',
    date: '2026-07-18',
    endDate: '2026-07-19',
    description: 'A two-day immersive wellness experience featuring yoga, meditation, sound healing, plant medicine education, and holistic health workshops in a beautiful outdoor setting.',
    tags: ['wellness', 'yoga', 'meditation', 'healing', 'outdoor'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Portland Wellness Collective',
    vendorOpportunities: true,
    emoji: '🧘'
  },
  {
    id: 'nash-music-001',
    title: 'Nashville CMA Fest',
    category: 'Music',
    city: 'Nashville',
    state: 'Tennessee',
    stateCode: 'TN',
    date: '2026-06-04',
    endDate: '2026-06-07',
    description: 'The world\'s biggest country music festival takes over downtown Nashville. Fan-focused with meet-and-greets, intimate performances, and massive headliner shows at Nissan Stadium.',
    tags: ['country', 'music', 'multi-day', 'stadium'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Paid',
    organizer: 'Country Music Association',
    vendorOpportunities: true,
    emoji: '🎸'
  },
  {
    id: 'nash-food-001',
    title: 'Nashville Hot Chicken Festival',
    category: 'Food',
    city: 'Nashville',
    state: 'Tennessee',
    stateCode: 'TN',
    date: '2026-07-04',
    endDate: '2026-07-04',
    description: 'Celebrate Nashville\'s most iconic dish at this beloved annual festival. Dozens of local restaurants compete for the best hot chicken crown while live music fills the air.',
    tags: ['food', 'free', 'local', 'outdoor', 'competition'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'Nashville Convention & Visitors Corp',
    vendorOpportunities: false,
    emoji: '🍗'
  },
  {
    id: 'mia-cultural-001',
    title: 'Miami Calle Ocho Festival',
    category: 'Cultural',
    city: 'Miami',
    state: 'Florida',
    stateCode: 'FL',
    date: '2026-03-08',
    endDate: '2026-03-08',
    description: 'The largest Hispanic festival in the US, stretching 23 blocks through the heart of Little Havana. Salsa dancing, world-class Cuban food, live music, and a spectacular celebration of Latin culture.',
    tags: ['cultural', 'latin', 'music', 'food', 'free', 'community'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Free',
    organizer: 'Kiwanis Club of Little Havana',
    vendorOpportunities: true,
    emoji: '💃'
  },
  {
    id: 'mia-art-001',
    title: 'Art Basel Miami Beach',
    category: 'Art',
    city: 'Miami',
    state: 'Florida',
    stateCode: 'FL',
    date: '2026-12-03',
    endDate: '2026-12-06',
    description: 'The premier art event of the Western Hemisphere. Galleries from around the world present paintings, sculptures, installations, and digital art at the Miami Beach Convention Center.',
    tags: ['art', 'international', 'galleries', 'contemporary', 'luxury'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Paid',
    organizer: 'MCH Group AG',
    vendorOpportunities: false,
    emoji: '🖼️'
  },
  {
    id: 'den-music-001',
    title: 'Denver Underground Music Showcase',
    category: 'Music',
    city: 'Denver',
    state: 'Colorado',
    stateCode: 'CO',
    date: '2026-07-23',
    endDate: '2026-07-26',
    description: 'The largest multi-venue music festival in the Rocky Mountain region, featuring 400+ bands across 30+ venues along South Broadway. A true city-wide music experience.',
    tags: ['music', 'indie', 'multi-venue', 'local', 'underground'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Underground Music Showcase LLC',
    vendorOpportunities: true,
    emoji: '🎶'
  },
  {
    id: 'den-wellness-001',
    title: 'Colorado Yoga & Wellness Festival',
    category: 'Wellness',
    city: 'Denver',
    state: 'Colorado',
    stateCode: 'CO',
    date: '2026-08-21',
    endDate: '2026-08-23',
    description: 'Three days of yoga, mindfulness, meditation, and holistic health in the beautiful Rocky Mountain foothills. Over 100 classes, workshops, and experiences for all levels.',
    tags: ['wellness', 'yoga', 'mindfulness', 'mountains', 'outdoor'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Colorado Wellness Network',
    vendorOpportunities: true,
    emoji: '🏔️'
  },
  {
    id: 'den-spiritual-001',
    title: 'Denver Holistic Arts & Spiritual Fair',
    category: 'Spiritual',
    city: 'Denver',
    state: 'Colorado',
    stateCode: 'CO',
    date: '2026-09-19',
    endDate: '2026-09-20',
    description: 'Explore crystals, energy healing, tarot, astrology, shamanic practices, and alternative spirituality. Connect with practitioners, teachers, and like-minded seekers in a welcoming space.',
    tags: ['spiritual', 'holistic', 'healing', 'metaphysical', 'community'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'Denver Spiritual Arts Collective',
    vendorOpportunities: true,
    emoji: '✨'
  },
  {
    id: 'phi-cultural-001',
    title: 'Philadelphia Odunde Festival',
    category: 'Cultural',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    stateCode: 'PA',
    date: '2026-06-14',
    endDate: '2026-06-14',
    description: 'The largest African-American street festival in the nation, celebrating African culture and heritage with traditional Yoruba ceremonies, African crafts, food, and live music.',
    tags: ['cultural', 'african', 'heritage', 'music', 'free', 'community'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'ODUNDE Inc.',
    vendorOpportunities: true,
    emoji: '🌍'
  },
  {
    id: 'phi-food-001',
    title: 'Philly Restaurant Week',
    category: 'Food',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    stateCode: 'PA',
    date: '2026-01-16',
    endDate: '2026-01-25',
    description: 'Discover Philadelphia\'s incredible dining scene during Restaurant Week, when top restaurants offer special prix-fixe menus at exceptional prices. Over 150 restaurants participate.',
    tags: ['food', 'dining', 'restaurants', 'prix-fixe'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Visit Philadelphia',
    vendorOpportunities: false,
    emoji: '🥗'
  },
  {
    id: 'phi-art-001',
    title: 'Philadelphia International Festival of the Arts',
    category: 'Art',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    stateCode: 'PA',
    date: '2026-04-17',
    endDate: '2026-04-26',
    description: 'A 10-day festival featuring dance, theater, music, film, and visual arts from artists around the world, transforming Philadelphia into a global stage.',
    tags: ['art', 'theater', 'dance', 'film', 'international'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Kimmel Center for the Performing Arts',
    vendorOpportunities: false,
    emoji: '🎭'
  },
  {
    id: 'det-music-001',
    title: 'Movement Electronic Music Festival',
    category: 'Music',
    city: 'Detroit',
    state: 'Michigan',
    stateCode: 'MI',
    date: '2026-05-23',
    endDate: '2026-05-25',
    description: 'The world\'s premier electronic music festival, held on the Detroit riverfront. A celebration of Detroit techno and its global influence, featuring DJs and live acts from around the world.',
    tags: ['electronic', 'techno', 'music', 'outdoor', 'waterfront'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Paid',
    organizer: 'Paxahau Events',
    vendorOpportunities: true,
    emoji: '🎧'
  },
  {
    id: 'det-cultural-001',
    title: 'Detroit Windsor International Freedom Festival',
    category: 'Cultural',
    city: 'Detroit',
    state: 'Michigan',
    stateCode: 'MI',
    date: '2026-07-04',
    endDate: '2026-07-04',
    description: 'The largest fireworks display in North America lights up the Detroit River on Independence Day, celebrating the friendship between the United States and Canada.',
    tags: ['cultural', 'fireworks', 'free', 'family', 'independence day'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'Metro Detroit & Windsor Tourism',
    vendorOpportunities: false,
    emoji: '🎆'
  },
  {
    id: 'det-wellness-001',
    title: 'Detroit Yoga & Wellness Summit',
    category: 'Wellness',
    city: 'Detroit',
    state: 'Michigan',
    stateCode: 'MI',
    date: '2026-09-12',
    endDate: '2026-09-13',
    description: 'A weekend of transformative wellness practices rooted in Detroit\'s spirit of resilience. Yoga, breathwork, sound baths, nutrition workshops, and community connection.',
    tags: ['wellness', 'yoga', 'community', 'healing', 'urban'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Detroit Wellness Collective',
    vendorOpportunities: true,
    emoji: '🌿'
  },
  {
    id: 'nash-spiritual-001',
    title: 'Nashville Conscious Living Expo',
    category: 'Spiritual',
    city: 'Nashville',
    state: 'Tennessee',
    stateCode: 'TN',
    date: '2026-03-14',
    endDate: '2026-03-15',
    description: 'A gathering of seekers, healers, and teachers exploring consciousness, spirituality, and holistic living. Features speakers, workshops, a vendor marketplace, and energy healing sessions.',
    tags: ['spiritual', 'conscious', 'holistic', 'healing', 'expo'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Nashville Holistic Arts',
    vendorOpportunities: true,
    emoji: '🌙'
  },
  {
    id: 'mia-wellness-001',
    title: 'Miami Wellness & Health Festival',
    category: 'Wellness',
    city: 'Miami',
    state: 'Florida',
    stateCode: 'FL',
    date: '2026-02-21',
    endDate: '2026-02-22',
    description: 'A vibrant celebration of health, wellness, and conscious living on the beach. Yoga on the sand, smoothie competitions, fitness demos, and a thriving wellness marketplace.',
    tags: ['wellness', 'beach', 'yoga', 'fitness', 'outdoor'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Paid',
    organizer: 'Miami Health Initiative',
    vendorOpportunities: true,
    emoji: '🌊'
  },
  {
    id: 'nola-spiritual-001',
    title: 'New Orleans Voodoo Music + Arts Experience',
    category: 'Spiritual',
    city: 'New Orleans',
    state: 'Louisiana',
    stateCode: 'LA',
    date: '2026-10-30',
    endDate: '2026-11-01',
    description: 'Halloween weekend in New Orleans becomes a festival of music, art, and mystery. Celebrating the spiritual heritage and creative energy of the Crescent City across City Park.',
    tags: ['music', 'art', 'spiritual', 'halloween', 'outdoor', 'multi-day'],
    ticketUrl: '#',
    featured: true,
    image: null,
    price: 'Paid',
    organizer: 'Voodoo Experiences LLC',
    vendorOpportunities: true,
    emoji: '🎭'
  },
  {
    id: 'chi-wellness-001',
    title: 'Chicago Summer Wellness Fest',
    category: 'Wellness',
    city: 'Chicago',
    state: 'Illinois',
    stateCode: 'IL',
    date: '2026-07-25',
    endDate: '2026-07-26',
    description: 'Chicago\'s lakefront transforms into a wellness oasis with yoga classes, meditation circles, fitness challenges, plant-based food vendors, and holistic health practitioners.',
    tags: ['wellness', 'lakefront', 'yoga', 'outdoor', 'free'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'Chicago Park District',
    vendorOpportunities: true,
    emoji: '🌞'
  },
  {
    id: 'pdx-food-001',
    title: 'Portland Night Market',
    category: 'Food',
    city: 'Portland',
    state: 'Oregon',
    stateCode: 'OR',
    date: '2026-08-07',
    endDate: '2026-08-09',
    description: 'A vibrant celebration of Asian-Pacific culture and cuisine under the stars. Over 100 vendors offering food, art, music, and community in the heart of Old Town Chinatown.',
    tags: ['food', 'cultural', 'night', 'asian', 'art', 'community'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'Pacific Islander / Asian Community Network',
    vendorOpportunities: true,
    emoji: '🏮'
  },
  {
    id: 'atl-art-001',
    title: 'Atlanta Jazz Festival',
    category: 'Art',
    city: 'Atlanta',
    state: 'Georgia',
    stateCode: 'GA',
    date: '2026-05-22',
    endDate: '2026-05-25',
    description: 'One of the largest free jazz festivals in the US, held over Memorial Day weekend in Piedmont Park. Four days of world-class jazz, blues, and R&B under the Atlanta sky.',
    tags: ['jazz', 'music', 'free', 'outdoor', 'memorial day'],
    ticketUrl: '#',
    featured: false,
    image: null,
    price: 'Free',
    organizer: 'City of Atlanta Office of Cultural Affairs',
    vendorOpportunities: true,
    emoji: '🎷'
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { FESTIVALS_DATA };
}
