// FestivalCalendar.online — Festival Data
// 100 real US festivals with approximate 2026 dates
// datesApproximate: true on all entries

window.FESTIVALS_DATA = [

  // ── STATE CAPITAL FESTIVALS (50) ──────────────────────────────────────────

  {
    id: "jubilee-cityfest-2026",
    title: "Jubilee CityFest",
    category: "Music",
    city: "Montgomery",
    state: "Alabama",
    stateCode: "AL",
    date: "2026-05-22",
    endDate: "2026-05-24",
    description: "Montgomery's signature outdoor music festival on the banks of the Alabama River, featuring national headliners and local acts across multiple stages.",
    tags: ["music", "outdoor", "family", "alabama"],
    ticketUrl: "https://jubileecityfest.com",
    featured: false,
    image: "",
    price: "$25–$75",
    organizer: "City of Montgomery",
    vendorOpportunities: true,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "alaska-folk-festival-2026",
    title: "Alaska Folk Festival",
    category: "Music",
    city: "Juneau",
    state: "Alaska",
    stateCode: "AK",
    date: "2026-04-06",
    endDate: "2026-04-11",
    description: "A beloved week-long celebration of folk music, dance, and Alaskan traditions drawing musicians from across the state to Juneau's Centennial Hall.",
    tags: ["folk", "dance", "free", "alaska", "community"],
    ticketUrl: "https://alaskafolkfestival.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Alaska Folk Festival",
    vendorOpportunities: false,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "mcdowell-mountain-music-2026",
    title: "McDowell Mountain Music Festival",
    category: "Music",
    city: "Phoenix",
    state: "Arizona",
    stateCode: "AZ",
    date: "2026-03-06",
    endDate: "2026-03-08",
    description: "A community-focused outdoor music festival in Phoenix raising funds for local charities, with eclectic lineups across multiple stages in the desert.",
    tags: ["music", "outdoor", "charity", "arizona", "indie"],
    ticketUrl: "https://m3fest.com",
    featured: false,
    image: "",
    price: "$60–$150",
    organizer: "M3F",
    vendorOpportunities: true,
    emoji: "🌵",
    datesApproximate: true
  },
  {
    id: "little-rock-film-festival-2026",
    title: "Little Rock Film Festival",
    category: "Art",
    city: "Little Rock",
    state: "Arkansas",
    stateCode: "AR",
    date: "2026-04-22",
    endDate: "2026-04-26",
    description: "Arkansas's premier film festival showcasing independent cinema, documentary films, and live music in the heart of downtown Little Rock.",
    tags: ["film", "art", "indie", "arkansas", "cinema"],
    ticketUrl: "https://littlerockfilmfestival.com",
    featured: false,
    image: "",
    price: "$10–$50",
    organizer: "Little Rock Film Festival",
    vendorOpportunities: false,
    emoji: "🎬",
    datesApproximate: true
  },
  {
    id: "sacramento-music-festival-2026",
    title: "Sacramento Music Festival",
    category: "Music",
    city: "Sacramento",
    state: "California",
    stateCode: "CA",
    date: "2026-05-22",
    endDate: "2026-05-25",
    description: "One of the world's largest traditional jazz festivals, filling Old Sacramento's historic streets with Dixieland, swing, and classic jazz across indoor and outdoor venues.",
    tags: ["jazz", "dixieland", "historic", "california", "outdoor"],
    ticketUrl: "https://sacmusicfest.com",
    featured: false,
    image: "",
    price: "$30–$100",
    organizer: "Sacramento Traditional Jazz Society",
    vendorOpportunities: true,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "taste-of-colorado-2026",
    title: "A Taste of Colorado",
    category: "Food",
    city: "Denver",
    state: "Colorado",
    stateCode: "CO",
    date: "2026-09-05",
    endDate: "2026-09-07",
    description: "Denver's landmark Labor Day festival celebrating Colorado's diverse culinary scene with 50+ restaurants, live music on multiple stages, and family activities in Civic Center Park.",
    tags: ["food", "free", "family", "colorado", "culinary"],
    ticketUrl: "https://atasteofcolorado.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Civic Center Conservancy",
    vendorOpportunities: true,
    emoji: "🍽️",
    datesApproximate: true
  },
  {
    id: "hartford-jazz-festival-2026",
    title: "Hartford Jazz Festival",
    category: "Music",
    city: "Hartford",
    state: "Connecticut",
    stateCode: "CT",
    date: "2026-07-10",
    endDate: "2026-07-12",
    description: "A free summer jazz festival in downtown Hartford bringing world-class jazz artists to Bushnell Park for three days of outdoor performances.",
    tags: ["jazz", "free", "outdoor", "connecticut", "summer"],
    ticketUrl: "https://hartfordjazzfestival.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Hartford Jazz Society",
    vendorOpportunities: true,
    emoji: "🎺",
    datesApproximate: true
  },
  {
    id: "firefly-music-festival-2026",
    title: "Firefly Music Festival",
    category: "Music",
    city: "Dover",
    state: "Delaware",
    stateCode: "DE",
    date: "2026-06-18",
    endDate: "2026-06-21",
    description: "One of the East Coast's premier camping music festivals held at The Woodlands of Dover Downs, with massive headliners across seven stages over four days.",
    tags: ["music", "camping", "featured", "delaware", "indie", "pop", "rock"],
    ticketUrl: "https://fireflyfestival.com",
    featured: true,
    image: "",
    price: "$250–$450",
    organizer: "Firefly Music Festival",
    vendorOpportunities: true,
    emoji: "✨",
    datesApproximate: true
  },
  {
    id: "word-of-south-2026",
    title: "Word of South Festival",
    category: "Art",
    city: "Tallahassee",
    state: "Florida",
    stateCode: "FL",
    date: "2026-04-17",
    endDate: "2026-04-19",
    description: "A free festival at the intersection of literature and music on the grounds of the historic Governor's Club in Tallahassee, featuring authors, poets, and musicians.",
    tags: ["literature", "music", "free", "florida", "art"],
    ticketUrl: "https://wordofsouth.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Word of South",
    vendorOpportunities: false,
    emoji: "📚",
    datesApproximate: true
  },
  {
    id: "atlanta-jazz-festival-2026",
    title: "Atlanta Jazz Festival",
    category: "Music",
    city: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    date: "2026-05-22",
    endDate: "2026-05-25",
    description: "One of the largest free jazz festivals in the US, held over Memorial Day weekend in Piedmont Park with world-class jazz artists on multiple outdoor stages.",
    tags: ["jazz", "free", "outdoor", "georgia", "memorial day"],
    ticketUrl: "https://atlantafestivals.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "City of Atlanta",
    vendorOpportunities: true,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "aloha-festivals-2026",
    title: "Aloha Festivals",
    category: "Cultural",
    city: "Honolulu",
    state: "Hawaii",
    stateCode: "HI",
    date: "2026-09-12",
    endDate: "2026-09-20",
    description: "Hawaii's premier cultural celebration spanning multiple islands, honoring Hawaiian traditions, music, hula, and the spirit of Aloha through parades, floral displays, and performances.",
    tags: ["cultural", "free", "hawaii", "hula", "tradition"],
    ticketUrl: "https://alohafestivals.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Aloha Festivals",
    vendorOpportunities: true,
    emoji: "🌺",
    datesApproximate: true
  },
  {
    id: "treefort-music-fest-2026",
    title: "Treefort Music Fest",
    category: "Music",
    city: "Boise",
    state: "Idaho",
    stateCode: "ID",
    date: "2026-03-25",
    endDate: "2026-03-29",
    description: "Boise's beloved indie music and arts festival taking over the city's downtown with 400+ artists across 20+ venues, plus film, comedy, yoga, and food forts.",
    tags: ["indie", "music", "featured", "idaho", "arts", "multi-venue"],
    ticketUrl: "https://treefortmusicfest.com",
    featured: true,
    image: "",
    price: "$100–$175",
    organizer: "Treefort Music Fest",
    vendorOpportunities: true,
    emoji: "🌲",
    datesApproximate: true
  },
  {
    id: "illinois-state-fair-2026",
    title: "Illinois State Fair",
    category: "Cultural",
    city: "Springfield",
    state: "Illinois",
    stateCode: "IL",
    date: "2026-08-13",
    endDate: "2026-08-23",
    description: "One of America's oldest state fairs featuring grandstand concerts, agricultural exhibits, carnival rides, and Illinois food specialties drawing hundreds of thousands annually.",
    tags: ["state fair", "cultural", "family", "illinois", "food"],
    ticketUrl: "https://illinoisstatefair.org",
    featured: false,
    image: "",
    price: "$5–$15",
    organizer: "Illinois Department of Agriculture",
    vendorOpportunities: true,
    emoji: "🎡",
    datesApproximate: true
  },
  {
    id: "indy-jazz-fest-2026",
    title: "Indy Jazz Fest",
    category: "Music",
    city: "Indianapolis",
    state: "Indiana",
    stateCode: "IN",
    date: "2026-06-19",
    endDate: "2026-06-21",
    description: "Indianapolis's premier jazz festival drawing top national and international jazz artists to White River State Park for three days of world-class performances.",
    tags: ["jazz", "indiana", "outdoor", "music"],
    ticketUrl: "https://indyjazzfest.net",
    featured: false,
    image: "",
    price: "$30–$90",
    organizer: "Indy Jazz Fest",
    vendorOpportunities: true,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "80-35-music-festival-2026",
    title: "80/35 Music Festival",
    category: "Music",
    city: "Des Moines",
    state: "Iowa",
    stateCode: "IA",
    date: "2026-07-10",
    endDate: "2026-07-11",
    description: "Named for Iowa's two major highways, 80/35 is a two-day outdoor music festival in downtown Des Moines bringing national indie, rock, and alternative acts to Western Gateway Park.",
    tags: ["music", "indie", "rock", "iowa", "outdoor"],
    ticketUrl: "https://8035festival.com",
    featured: false,
    image: "",
    price: "$50–$90",
    organizer: "80/35 Music Festival",
    vendorOpportunities: true,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "fiesta-mexicana-topeka-2026",
    title: "Fiesta Mexicana",
    category: "Cultural",
    city: "Topeka",
    state: "Kansas",
    stateCode: "KS",
    date: "2026-07-08",
    endDate: "2026-07-12",
    description: "One of the oldest and largest Mexican cultural festivals in the Midwest, celebrating Hispanic heritage with authentic food, music, dance, and the iconic Fiesta parade in Topeka.",
    tags: ["cultural", "free", "hispanic", "kansas", "food", "dance"],
    ticketUrl: "https://ourladyofguadalupe-ks.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Our Lady of Guadalupe Parish",
    vendorOpportunities: true,
    emoji: "🌮",
    datesApproximate: true
  },
  {
    id: "kentucky-roots-music-festival-2026",
    title: "Kentucky Roots Music Festival",
    category: "Music",
    city: "Frankfort",
    state: "Kentucky",
    stateCode: "KY",
    date: "2026-06-05",
    endDate: "2026-06-06",
    description: "A free outdoor festival celebrating Appalachian, bluegrass, and American roots music on the Capitol grounds in Frankfort, honoring Kentucky's deep musical heritage.",
    tags: ["bluegrass", "roots", "free", "kentucky", "appalachian"],
    ticketUrl: "https://kentuckyroots.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Kentucky Arts Council",
    vendorOpportunities: false,
    emoji: "🪕",
    datesApproximate: true
  },
  {
    id: "baton-rouge-blues-festival-2026",
    title: "Baton Rouge Blues Festival",
    category: "Music",
    city: "Baton Rouge",
    state: "Louisiana",
    stateCode: "LA",
    date: "2026-10-09",
    endDate: "2026-10-11",
    description: "A free outdoor blues festival celebrating Louisiana's deep blues tradition, held in downtown Baton Rouge with national and regional blues acts across two stages.",
    tags: ["blues", "free", "louisiana", "outdoor", "music"],
    ticketUrl: "https://batonrougebluesfestival.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Baton Rouge Blues Foundation",
    vendorOpportunities: true,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "augusta-river-fest-2026",
    title: "Augusta River Fest",
    category: "Cultural",
    city: "Augusta",
    state: "Maine",
    stateCode: "ME",
    date: "2026-07-11",
    endDate: "2026-07-12",
    description: "A free community celebration along the Kennebec River in Augusta featuring live music, local food vendors, artisan crafts, and family activities celebrating Maine's river heritage.",
    tags: ["cultural", "free", "maine", "community", "family"],
    ticketUrl: "https://augustariverfest.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "City of Augusta",
    vendorOpportunities: true,
    emoji: "🌊",
    datesApproximate: true
  },
  {
    id: "chesapeake-bay-blues-festival-2026",
    title: "Chesapeake Bay Blues Festival",
    category: "Music",
    city: "Annapolis",
    state: "Maryland",
    stateCode: "MD",
    date: "2026-06-12",
    endDate: "2026-06-14",
    description: "A legendary free blues festival held on the banks of the Chesapeake Bay in Sandy Point State Park, drawing top blues artists from around the country.",
    tags: ["blues", "free", "maryland", "outdoor", "bay"],
    ticketUrl: "https://chesapeakebaybluesfestival.com",
    featured: false,
    image: "",
    price: "Free (park admission)",
    organizer: "Chesapeake Bay Blues Festival",
    vendorOpportunities: true,
    emoji: "🎶",
    datesApproximate: true
  },
  {
    id: "boston-calling-2026",
    title: "Boston Calling Music Festival",
    category: "Music",
    city: "Boston",
    state: "Massachusetts",
    stateCode: "MA",
    date: "2026-05-22",
    endDate: "2026-05-24",
    description: "New England's biggest music festival held at Harvard Athletic Complex, featuring three days of rock, indie, hip-hop, and electronic music with massive headliners.",
    tags: ["music", "rock", "indie", "massachusetts", "memorial day"],
    ticketUrl: "https://bostoncalling.com",
    featured: false,
    image: "",
    price: "$175–$375",
    organizer: "Boston Calling Events",
    vendorOpportunities: true,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "common-ground-music-festival-2026",
    title: "Common Ground Music Festival",
    category: "Music",
    city: "Lansing",
    state: "Michigan",
    stateCode: "MI",
    date: "2026-07-14",
    endDate: "2026-07-18",
    description: "A free five-day outdoor music festival in Lansing's Adado Riverfront Park featuring national acts across multiple genres — rock, country, hip-hop, and more.",
    tags: ["music", "free", "michigan", "outdoor", "multi-genre"],
    ticketUrl: "https://commongroundfest.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Common Ground Music Festival",
    vendorOpportunities: true,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "twin-cities-jazz-festival-2026",
    title: "Twin Cities Jazz Festival",
    category: "Music",
    city: "Saint Paul",
    state: "Minnesota",
    stateCode: "MN",
    date: "2026-06-26",
    endDate: "2026-06-28",
    description: "A free outdoor jazz festival in the heart of Saint Paul's Mears Park, featuring local, national, and international jazz artists across multiple outdoor stages.",
    tags: ["jazz", "free", "minnesota", "outdoor", "music"],
    ticketUrl: "https://hotsummerjazz.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Twin Cities Jazz Festival",
    vendorOpportunities: true,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "mississippi-state-fair-2026",
    title: "Mississippi State Fair",
    category: "Cultural",
    city: "Jackson",
    state: "Mississippi",
    stateCode: "MS",
    date: "2026-10-01",
    endDate: "2026-10-11",
    description: "One of the South's most beloved state fairs with grandstand entertainment, carnival rides, agricultural exhibits, and classic Mississippi fair food at the State Fairgrounds in Jackson.",
    tags: ["state fair", "cultural", "family", "mississippi", "food"],
    ticketUrl: "https://msstatefair.com",
    featured: false,
    image: "",
    price: "$8–$15",
    organizer: "Mississippi Fair Commission",
    vendorOpportunities: true,
    emoji: "🎡",
    datesApproximate: true
  },
  {
    id: "missouri-river-festival-of-arts-2026",
    title: "Missouri River Festival of the Arts",
    category: "Art",
    city: "Jefferson City",
    state: "Missouri",
    stateCode: "MO",
    date: "2026-08-08",
    endDate: "2026-08-09",
    description: "An annual arts festival along the Missouri River celebrating fine art, crafts, and live music in Missouri's capital city, featuring juried artists and local performers.",
    tags: ["art", "crafts", "missouri", "outdoor", "music"],
    ticketUrl: "https://moriverartscouncil.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Missouri River Regional Arts Council",
    vendorOpportunities: true,
    emoji: "🎨",
    datesApproximate: true
  },
  {
    id: "last-chance-stampede-fair-2026",
    title: "Last Chance Stampede and Fair",
    category: "Cultural",
    city: "Helena",
    state: "Montana",
    stateCode: "MT",
    date: "2026-07-22",
    endDate: "2026-07-26",
    description: "Montana's signature summer fair and rodeo in Helena, featuring a PRCA rodeo, carnival rides, grandstand entertainment, and classic Montana ranch culture.",
    tags: ["rodeo", "state fair", "cultural", "montana", "family"],
    ticketUrl: "https://lcsf.org",
    featured: false,
    image: "",
    price: "$10–$20",
    organizer: "Lewis and Clark Fairgrounds",
    vendorOpportunities: true,
    emoji: "🤠",
    datesApproximate: true
  },
  {
    id: "lincoln-calling-2026",
    title: "Lincoln Calling",
    category: "Music",
    city: "Lincoln",
    state: "Nebraska",
    stateCode: "NE",
    date: "2026-09-30",
    endDate: "2026-10-03",
    description: "Lincoln's indie music and arts festival taking over multiple downtown venues for four days of local and national acts, art installations, and community events.",
    tags: ["indie", "music", "multi-venue", "nebraska", "arts"],
    ticketUrl: "https://lincolncalling.com",
    featured: false,
    image: "",
    price: "$40–$75",
    organizer: "Lincoln Calling",
    vendorOpportunities: false,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "nevada-day-celebration-2026",
    title: "Nevada Day Celebration",
    category: "Cultural",
    city: "Carson City",
    state: "Nevada",
    stateCode: "NV",
    date: "2026-10-30",
    endDate: "2026-10-31",
    description: "Nevada's official state holiday celebration in Carson City featuring the largest Nevada Day Parade, carnival, live entertainment, and celebrations of the Silver State's heritage.",
    tags: ["cultural", "free", "nevada", "parade", "state holiday"],
    ticketUrl: "https://nevadaday.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Nevada Day Committee",
    vendorOpportunities: true,
    emoji: "🥈",
    datesApproximate: true
  },
  {
    id: "market-days-festival-2026",
    title: "Market Days Festival",
    category: "Cultural",
    city: "Concord",
    state: "New Hampshire",
    stateCode: "NH",
    date: "2026-06-19",
    endDate: "2026-06-20",
    description: "A beloved New Hampshire tradition transforming downtown Concord into an open-air marketplace and festival with local vendors, artisans, live music, and family entertainment.",
    tags: ["cultural", "free", "new hampshire", "community", "artisan"],
    ticketUrl: "https://concordnh.gov",
    featured: false,
    image: "",
    price: "Free",
    organizer: "City of Concord",
    vendorOpportunities: true,
    emoji: "🛍️",
    datesApproximate: true
  },
  {
    id: "trenton-punk-rock-flea-market-2026",
    title: "Trenton Punk Rock Flea Market",
    category: "Cultural",
    city: "Trenton",
    state: "New Jersey",
    stateCode: "NJ",
    date: "2026-06-20",
    endDate: "2026-06-21",
    description: "A massive alternative flea market at Arm & Hammer Park featuring hundreds of vendors selling records, vintage clothing, art, and curiosities alongside live punk and alternative music.",
    tags: ["punk", "flea market", "alternative", "new jersey", "music", "art"],
    ticketUrl: "https://punkrockfleamarket.com",
    featured: false,
    image: "",
    price: "$10–$20",
    organizer: "Punk Rock Flea Market",
    vendorOpportunities: true,
    emoji: "🤘",
    datesApproximate: true
  },
  {
    id: "santa-fe-folk-art-market-2026",
    title: "Santa Fe International Folk Art Market",
    category: "Cultural",
    city: "Santa Fe",
    state: "New Mexico",
    stateCode: "NM",
    date: "2026-07-11",
    endDate: "2026-07-12",
    description: "The world's largest international folk art market on Museum Hill in Santa Fe, featuring 150+ master folk artists from 50+ countries with traditional crafts, textiles, and ceramics.",
    tags: ["folk art", "cultural", "international", "new mexico", "crafts"],
    ticketUrl: "https://folkartmarket.org",
    featured: false,
    image: "",
    price: "$20–$30",
    organizer: "Museum of International Folk Art",
    vendorOpportunities: false,
    emoji: "🏺",
    datesApproximate: true
  },
  {
    id: "albany-tulip-festival-2026",
    title: "Albany Tulip Festival",
    category: "Cultural",
    city: "Albany",
    state: "New York",
    stateCode: "NY",
    date: "2026-05-08",
    endDate: "2026-05-10",
    description: "Albany's oldest festival celebrating the city's Dutch heritage with the crowning of the Tulip Queen, tulip gardens in Washington Park, live music, and Dutch-inspired food and crafts.",
    tags: ["cultural", "free", "new york", "dutch heritage", "outdoor"],
    ticketUrl: "https://albanytulipfestival.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "City of Albany",
    vendorOpportunities: true,
    emoji: "🌷",
    datesApproximate: true
  },
  {
    id: "hopscotch-music-festival-2026",
    title: "Hopscotch Music Festival",
    category: "Music",
    city: "Raleigh",
    state: "North Carolina",
    stateCode: "NC",
    date: "2026-09-10",
    endDate: "2026-09-12",
    description: "Raleigh's premier indie and experimental music festival taking over downtown venues with an eclectic lineup spanning indie rock, hip-hop, electronic, and avant-garde acts.",
    tags: ["indie", "music", "multi-venue", "north carolina", "experimental"],
    ticketUrl: "https://hopscotchmusic.com",
    featured: false,
    image: "",
    price: "$75–$150",
    organizer: "Hopscotch Music Festival",
    vendorOpportunities: false,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "united-tribes-powwow-2026",
    title: "United Tribes International Powwow",
    category: "Cultural",
    city: "Bismarck",
    state: "North Dakota",
    stateCode: "ND",
    date: "2026-09-10",
    endDate: "2026-09-12",
    description: "One of the largest Native American powwows in the US, held at United Tribes Technical College in Bismarck, celebrating Indigenous dance, drumming, art, and culture.",
    tags: ["cultural", "free", "native american", "north dakota", "powwow"],
    ticketUrl: "https://unitedtribespowwow.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "United Tribes Technical College",
    vendorOpportunities: true,
    emoji: "🪶",
    datesApproximate: true
  },
  {
    id: "columbus-arts-festival-2026",
    title: "Columbus Arts Festival",
    category: "Art",
    city: "Columbus",
    state: "Ohio",
    stateCode: "OH",
    date: "2026-06-05",
    endDate: "2026-06-07",
    description: "One of the top fine arts festivals in the Midwest, lining the Scioto riverbanks in Columbus with 200+ juried artists, live performances, culinary arts, and family activities.",
    tags: ["art", "free", "ohio", "outdoor", "juried"],
    ticketUrl: "https://gcac.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Greater Columbus Arts Council",
    vendorOpportunities: false,
    emoji: "🎨",
    datesApproximate: true
  },
  {
    id: "red-earth-festival-2026",
    title: "Red Earth Festival",
    category: "Cultural",
    city: "Oklahoma City",
    state: "Oklahoma",
    stateCode: "OK",
    date: "2026-06-05",
    endDate: "2026-06-07",
    description: "One of the world's most prestigious Native American arts festivals held in Oklahoma City, featuring a grand parade, dance competition, fine art market, and cultural demonstrations.",
    tags: ["cultural", "native american", "oklahoma", "art", "dance"],
    ticketUrl: "https://redearth.org",
    featured: false,
    image: "",
    price: "$10–$20",
    organizer: "Red Earth, Inc.",
    vendorOpportunities: true,
    emoji: "🪶",
    datesApproximate: true
  },
  {
    id: "oregon-state-fair-2026",
    title: "Oregon State Fair",
    category: "Cultural",
    city: "Salem",
    state: "Oregon",
    stateCode: "OR",
    date: "2026-08-28",
    endDate: "2026-09-07",
    description: "Oregon's beloved state fair at the Oregon State Fairgrounds in Salem, featuring concerts, carnival rides, agricultural competitions, Oregon-grown food, and family fun.",
    tags: ["state fair", "cultural", "family", "oregon", "food"],
    ticketUrl: "https://oregonstatefair.org",
    featured: false,
    image: "",
    price: "$10–$15",
    organizer: "Oregon State Fair",
    vendorOpportunities: true,
    emoji: "🎡",
    datesApproximate: true
  },
  {
    id: "kipona-festival-2026",
    title: "Kipona Festival",
    category: "Cultural",
    city: "Harrisburg",
    state: "Pennsylvania",
    stateCode: "PA",
    date: "2026-09-05",
    endDate: "2026-09-07",
    description: "Harrisburg's Labor Day tradition along Riverfront Park featuring live music, canoe and kayak races on the Susquehanna River, food vendors, and family activities.",
    tags: ["cultural", "free", "pennsylvania", "outdoor", "water sports"],
    ticketUrl: "https://harrisburgpa.gov",
    featured: false,
    image: "",
    price: "Free",
    organizer: "City of Harrisburg",
    vendorOpportunities: true,
    emoji: "🛶",
    datesApproximate: true
  },
  {
    id: "waterfire-providence-2026",
    title: "WaterFire Providence",
    category: "Art",
    city: "Providence",
    state: "Rhode Island",
    stateCode: "RI",
    date: "2026-07-18",
    endDate: "2026-07-18",
    description: "A stunning site-specific art installation lighting 100 bonfires on the rivers of downtown Providence, accompanied by ambient world music — one of America's most celebrated public art events.",
    tags: ["art", "free", "rhode island", "fire", "installation"],
    ticketUrl: "https://waterfire.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "WaterFire Providence",
    vendorOpportunities: false,
    emoji: "🔥",
    datesApproximate: true
  },
  {
    id: "indie-grits-festival-2026",
    title: "Indie Grits Festival",
    category: "Art",
    city: "Columbia",
    state: "South Carolina",
    stateCode: "SC",
    date: "2026-04-24",
    endDate: "2026-04-26",
    description: "Columbia's indie film and arts festival celebrating Southern independent cinema, music, and culture through screenings, concerts, and community events across multiple venues.",
    tags: ["film", "art", "indie", "south carolina", "music"],
    ticketUrl: "https://indiegrits.org",
    featured: false,
    image: "",
    price: "$15–$40",
    organizer: "Nickelodeon Theatre",
    vendorOpportunities: false,
    emoji: "🎬",
    datesApproximate: true
  },
  {
    id: "oahe-days-2026",
    title: "Oahe Days",
    category: "Cultural",
    city: "Pierre",
    state: "South Dakota",
    stateCode: "SD",
    date: "2026-07-17",
    endDate: "2026-07-19",
    description: "Pierre's signature summer celebration on the Missouri River featuring hydroplane boat races on Lake Oahe, carnival, live music, parade, and fireworks — a South Dakota tradition.",
    tags: ["cultural", "free", "south dakota", "outdoor", "water sports"],
    ticketUrl: "https://oahedays.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Oahe Days Committee",
    vendorOpportunities: true,
    emoji: "🚤",
    datesApproximate: true
  },
  {
    id: "cma-music-festival-2026",
    title: "CMA Music Festival",
    category: "Music",
    city: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    date: "2026-06-04",
    endDate: "2026-06-07",
    description: "The world's biggest country music event, filling Nashville's Nissan Stadium and downtown streets with A-list country stars, emerging artists, and legendary fan experiences.",
    tags: ["country", "music", "tennessee", "featured", "nashville"],
    ticketUrl: "https://cmaworld.com",
    featured: true,
    image: "",
    price: "$125–$325",
    organizer: "Country Music Association",
    vendorOpportunities: true,
    emoji: "🤠",
    datesApproximate: true
  },
  {
    id: "sxsw-2026",
    title: "SXSW",
    category: "Cultural",
    city: "Austin",
    state: "Texas",
    stateCode: "TX",
    date: "2026-03-13",
    endDate: "2026-03-22",
    description: "The world's most influential convergence of music, film, tech, and culture transforming Austin for 10 days with hundreds of official showcases, screenings, keynotes, and parties.",
    tags: ["music", "film", "tech", "featured", "texas", "multi-genre"],
    ticketUrl: "https://sxsw.com",
    featured: true,
    image: "",
    price: "$350–$1650",
    organizer: "SXSW, LLC",
    vendorOpportunities: true,
    emoji: "🎪",
    datesApproximate: true
  },
  {
    id: "utah-arts-festival-2026",
    title: "Utah Arts Festival",
    category: "Art",
    city: "Salt Lake City",
    state: "Utah",
    stateCode: "UT",
    date: "2026-06-25",
    endDate: "2026-06-28",
    description: "Utah's premier outdoor arts festival in Library Square, Salt Lake City, featuring 200+ visual artists, live performances across multiple stages, and interactive arts experiences.",
    tags: ["art", "utah", "outdoor", "music"],
    ticketUrl: "https://uaf.org",
    featured: false,
    image: "",
    price: "$10",
    organizer: "Utah Arts Festival",
    vendorOpportunities: false,
    emoji: "🎨",
    datesApproximate: true
  },
  {
    id: "vermont-jazz-center-summer-week-2026",
    title: "Vermont Jazz Center Summer Jazz Week",
    category: "Music",
    city: "Montpelier",
    state: "Vermont",
    stateCode: "VT",
    date: "2026-06-14",
    endDate: "2026-06-20",
    description: "An immersive jazz education and performance week in Vermont's capital, featuring workshops, masterclasses, and public concerts by visiting jazz masters and students.",
    tags: ["jazz", "music", "vermont", "education", "workshop"],
    ticketUrl: "https://vtjazz.org",
    featured: false,
    image: "",
    price: "$15–$40",
    organizer: "Vermont Jazz Center",
    vendorOpportunities: false,
    emoji: "🎺",
    datesApproximate: true
  },
  {
    id: "richmond-folk-festival-2026",
    title: "Richmond Folk Festival",
    category: "Cultural",
    city: "Richmond",
    state: "Virginia",
    stateCode: "VA",
    date: "2026-10-09",
    endDate: "2026-10-11",
    description: "One of the nation's premier free folk festivals on Richmond's riverfront, celebrating traditional music and dance from across America and around the world on six stages.",
    tags: ["folk", "cultural", "free", "featured", "virginia", "outdoor"],
    ticketUrl: "https://richmondfolkfestival.org",
    featured: true,
    image: "",
    price: "Free",
    organizer: "Venture Richmond",
    vendorOpportunities: true,
    emoji: "🌍",
    datesApproximate: true
  },
  {
    id: "procession-of-the-species-2026",
    title: "Procession of the Species",
    category: "Art",
    city: "Olympia",
    state: "Washington",
    stateCode: "WA",
    date: "2026-04-25",
    endDate: "2026-04-25",
    description: "A dazzling community-created pageant parade through downtown Olympia celebrating Earth Day with elaborate hand-crafted costumes depicting animals, plants, and natural phenomena.",
    tags: ["art", "parade", "free", "washington", "earth day", "community"],
    ticketUrl: "https://procession.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Earthbound Productions",
    vendorOpportunities: false,
    emoji: "🦋",
    datesApproximate: true
  },
  {
    id: "vandalia-gathering-2026",
    title: "Vandalia Gathering",
    category: "Cultural",
    city: "Charleston",
    state: "West Virginia",
    stateCode: "WV",
    date: "2026-05-22",
    endDate: "2026-05-25",
    description: "West Virginia's premier folk and traditional arts festival on the grounds of the State Capitol, celebrating Appalachian music, dance, crafts, and storytelling over Memorial Day weekend.",
    tags: ["folk", "cultural", "free", "west virginia", "appalachian"],
    ticketUrl: "https://wvculture.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "WV Division of Culture and History",
    vendorOpportunities: true,
    emoji: "🪕",
    datesApproximate: true
  },
  {
    id: "orton-park-festival-2026",
    title: "Orton Park Festival",
    category: "Music",
    city: "Madison",
    state: "Wisconsin",
    stateCode: "WI",
    date: "2026-08-28",
    endDate: "2026-08-30",
    description: "Madison's beloved free neighborhood music festival in historic Orton Park, featuring an eclectic lineup of folk, blues, jazz, and world music in a beautiful outdoor setting.",
    tags: ["music", "free", "wisconsin", "folk", "outdoor"],
    ticketUrl: "https://ortonparkfestival.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Willy Street Neighborhood",
    vendorOpportunities: true,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "cheyenne-frontier-days-2026",
    title: "Cheyenne Frontier Days",
    category: "Cultural",
    city: "Cheyenne",
    state: "Wyoming",
    stateCode: "WY",
    date: "2026-07-20",
    endDate: "2026-07-26",
    description: "The world's largest outdoor rodeo and western celebration — 'The Daddy of 'em All' — featuring PRCA championship rodeos, free pancake breakfasts, big-name country concerts, and parade.",
    tags: ["rodeo", "cultural", "wyoming", "country", "western"],
    ticketUrl: "https://cfdrodeo.com",
    featured: false,
    image: "",
    price: "$25–$75",
    organizer: "Cheyenne Frontier Days Committee",
    vendorOpportunities: true,
    emoji: "🤠",
    datesApproximate: true
  },

  // ── ADDITIONAL MAJOR CITY FESTIVALS (50) ─────────────────────────────────

  {
    id: "coachella-2026",
    title: "Coachella Valley Music and Arts Festival",
    category: "Music",
    city: "Indio",
    state: "California",
    stateCode: "CA",
    date: "2026-04-10",
    endDate: "2026-04-19",
    description: "The world's most iconic music and arts festival in the California desert, featuring globe-spanning headliners, massive art installations, and two weekends of unforgettable experiences.",
    tags: ["music", "art", "featured", "california", "desert", "electronic", "pop"],
    ticketUrl: "https://coachella.com",
    featured: true,
    image: "",
    price: "$500–$1200",
    organizer: "Goldenvoice",
    vendorOpportunities: true,
    emoji: "🌴",
    datesApproximate: true
  },
  {
    id: "lollapalooza-2026",
    title: "Lollapalooza",
    category: "Music",
    city: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    date: "2026-07-30",
    endDate: "2026-08-02",
    description: "One of America's original and most iconic music festivals, taking over Grant Park in Chicago for four days with 170+ acts across 8 stages spanning rock, hip-hop, EDM, and more.",
    tags: ["music", "rock", "featured", "illinois", "chicago", "hip-hop", "edm"],
    ticketUrl: "https://lollapalooza.com",
    featured: true,
    image: "",
    price: "$145–$475",
    organizer: "C3 Presents",
    vendorOpportunities: true,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "bonnaroo-2026",
    title: "Bonnaroo Music and Arts Festival",
    category: "Music",
    city: "Manchester",
    state: "Tennessee",
    stateCode: "TN",
    date: "2026-06-11",
    endDate: "2026-06-14",
    description: "A legendary four-day camping music and arts festival on a 700-acre farm in Tennessee, with 150+ performers across 10 stages blending rock, hip-hop, electronic, folk, and everything in between.",
    tags: ["music", "camping", "featured", "tennessee", "multi-genre", "arts"],
    ticketUrl: "https://bonnaroo.com",
    featured: true,
    image: "",
    price: "$250–$600",
    organizer: "Superfly + C3 Presents",
    vendorOpportunities: true,
    emoji: "🎪",
    datesApproximate: true
  },
  {
    id: "outside-lands-2026",
    title: "Outside Lands",
    category: "Music",
    city: "San Francisco",
    state: "California",
    stateCode: "CA",
    date: "2026-08-07",
    endDate: "2026-08-09",
    description: "San Francisco's premier music and arts festival nestled in Golden Gate Park, celebrating music, food, wine, comedy, and cannabis with world-class headliners and local culinary highlights.",
    tags: ["music", "food", "featured", "california", "san francisco", "arts"],
    ticketUrl: "https://sfoutsidelands.com",
    featured: true,
    image: "",
    price: "$175–$425",
    organizer: "Another Planet Entertainment",
    vendorOpportunities: true,
    emoji: "🌁",
    datesApproximate: true
  },
  {
    id: "governors-ball-2026",
    title: "Governors Ball Music Festival",
    category: "Music",
    city: "New York",
    state: "New York",
    stateCode: "NY",
    date: "2026-06-05",
    endDate: "2026-06-07",
    description: "New York City's flagship outdoor music festival at Flushing Meadows Corona Park in Queens, featuring three days of diverse headliners across multiple stages with the Manhattan skyline as backdrop.",
    tags: ["music", "featured", "new york", "pop", "rock", "hip-hop"],
    ticketUrl: "https://governorsballmusicfestival.com",
    featured: true,
    image: "",
    price: "$135–$375",
    organizer: "Founders Entertainment",
    vendorOpportunities: true,
    emoji: "🗽",
    datesApproximate: true
  },
  {
    id: "new-orleans-jazz-heritage-2026",
    title: "New Orleans Jazz & Heritage Festival",
    category: "Music",
    city: "New Orleans",
    state: "Louisiana",
    stateCode: "LA",
    date: "2026-04-24",
    endDate: "2026-05-03",
    description: "The crown jewel of American music festivals, Jazz Fest transforms the New Orleans Fair Grounds into a celebration of jazz, blues, gospel, zydeco, and Louisiana culture for two weekends.",
    tags: ["jazz", "blues", "featured", "louisiana", "new orleans", "gospel", "food"],
    ticketUrl: "https://nojazzfest.com",
    featured: true,
    image: "",
    price: "$85–$150",
    organizer: "Festival Productions",
    vendorOpportunities: true,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "ultra-miami-2026",
    title: "Ultra Music Festival",
    category: "Music",
    city: "Miami",
    state: "Florida",
    stateCode: "FL",
    date: "2026-03-27",
    endDate: "2026-03-29",
    description: "The world's premier electronic music festival in the heart of Miami, featuring three days of the globe's top DJs and producers across massive stages with stunning production.",
    tags: ["electronic", "edm", "music", "florida", "miami", "dance"],
    ticketUrl: "https://ultramusicfestival.com",
    featured: false,
    image: "",
    price: "$300–$1000",
    organizer: "Ultra Enterprises",
    vendorOpportunities: false,
    emoji: "🔊",
    datesApproximate: true
  },
  {
    id: "movement-detroit-2026",
    title: "Movement Electronic Music Festival",
    category: "Music",
    city: "Detroit",
    state: "Michigan",
    stateCode: "MI",
    date: "2026-05-23",
    endDate: "2026-05-25",
    description: "The birthplace of techno celebrates Memorial Day weekend with Movement, Detroit's iconic three-day electronic music festival at Hart Plaza overlooking the Detroit River.",
    tags: ["electronic", "techno", "music", "michigan", "detroit", "dance"],
    ticketUrl: "https://movement.us",
    featured: false,
    image: "",
    price: "$90–$200",
    organizer: "Paxahau",
    vendorOpportunities: false,
    emoji: "🎛️",
    datesApproximate: true
  },
  {
    id: "forecastle-festival-2026",
    title: "Forecastle Festival",
    category: "Music",
    city: "Louisville",
    state: "Kentucky",
    stateCode: "KY",
    date: "2026-07-17",
    endDate: "2026-07-19",
    description: "Louisville's beloved waterfront music festival at Waterfront Park, combining indie rock, alternative, and folk music with environmental activism and local Kentucky bourbon culture.",
    tags: ["music", "indie", "rock", "kentucky", "louisville", "waterfront"],
    ticketUrl: "https://forecastlefest.com",
    featured: false,
    image: "",
    price: "$90–$225",
    organizer: "AC Entertainment",
    vendorOpportunities: true,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "beale-street-music-festival-2026",
    title: "Beale Street Music Festival",
    category: "Music",
    city: "Memphis",
    state: "Tennessee",
    stateCode: "TN",
    date: "2026-05-01",
    endDate: "2026-05-03",
    description: "Memphis's signature music festival kicking off Memphis in May, featuring blues, rock, hip-hop, and soul on the banks of the Mississippi River at Tom Lee Park.",
    tags: ["blues", "music", "tennessee", "memphis", "outdoor", "soul"],
    ticketUrl: "https://memphisinmay.org",
    featured: false,
    image: "",
    price: "$40–$120",
    organizer: "Memphis in May International Festival",
    vendorOpportunities: true,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "south-beach-wine-food-2026",
    title: "South Beach Wine & Food Festival",
    category: "Food",
    city: "Miami Beach",
    state: "Florida",
    stateCode: "FL",
    date: "2026-02-19",
    endDate: "2026-02-22",
    description: "The nation's most star-studded culinary event on Miami's South Beach, drawing celebrity chefs, master sommeliers, and food lovers for tastings, dinners, and culinary demonstrations.",
    tags: ["food", "wine", "featured", "florida", "culinary", "celebrity chef"],
    ticketUrl: "https://sobefest.com",
    featured: true,
    image: "",
    price: "$100–$500",
    organizer: "SOBEWFF",
    vendorOpportunities: false,
    emoji: "🍷",
    datesApproximate: true
  },
  {
    id: "roots-picnic-2026",
    title: "The Roots Picnic",
    category: "Music",
    city: "Philadelphia",
    state: "Pennsylvania",
    stateCode: "PA",
    date: "2026-06-06",
    endDate: "2026-06-07",
    description: "Philadelphia's premier hip-hop and R&B festival curated by legendary duo The Roots at the Mann Center, blending music, food, culture, and community in a uniquely Philly way.",
    tags: ["hip-hop", "r&b", "music", "pennsylvania", "philadelphia", "soul"],
    ticketUrl: "https://rootspicnic.com",
    featured: false,
    image: "",
    price: "$85–$200",
    organizer: "Live Nation",
    vendorOpportunities: false,
    emoji: "🎤",
    datesApproximate: true
  },
  {
    id: "essence-festival-2026",
    title: "Essence Festival of Culture",
    category: "Cultural",
    city: "New Orleans",
    state: "Louisiana",
    stateCode: "LA",
    date: "2026-07-02",
    endDate: "2026-07-05",
    description: "The world's largest gathering celebrating Black culture and music — four days at the New Orleans Superdome and convention center with top R&B, hip-hop, and gospel acts, speakers, and empowerment expos.",
    tags: ["cultural", "r&b", "featured", "louisiana", "new orleans", "hip-hop", "gospel"],
    ticketUrl: "https://essencefestival.com",
    featured: true,
    image: "",
    price: "$125–$350",
    organizer: "Essence Communications",
    vendorOpportunities: true,
    emoji: "✨",
    datesApproximate: true
  },
  {
    id: "french-quarter-festival-2026",
    title: "French Quarter Festival",
    category: "Cultural",
    city: "New Orleans",
    state: "Louisiana",
    stateCode: "LA",
    date: "2026-04-02",
    endDate: "2026-04-05",
    description: "The world's largest free showcase of Louisiana music, transforming the entire French Quarter into an open-air festival with 20+ stages, 1,500+ musicians, and the best local food in the city.",
    tags: ["cultural", "free", "louisiana", "new orleans", "jazz", "zydeco", "food"],
    ticketUrl: "https://fqfi.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "French Quarter Festivals, Inc.",
    vendorOpportunities: true,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "edc-las-vegas-2026",
    title: "Electric Daisy Carnival (EDC) Las Vegas",
    category: "Music",
    city: "Las Vegas",
    state: "Nevada",
    stateCode: "NV",
    date: "2026-05-15",
    endDate: "2026-05-17",
    description: "The world's largest EDM festival under the electric sky at the Las Vegas Motor Speedway — three nights of the biggest names in electronic music, art cars, carnival rides, and 170,000+ daily attendees.",
    tags: ["electronic", "edm", "music", "nevada", "las vegas", "dance"],
    ticketUrl: "https://lasvegas.electricdaisycarnival.com",
    featured: false,
    image: "",
    price: "$350–$900",
    organizer: "Insomniac Events",
    vendorOpportunities: false,
    emoji: "⚡",
    datesApproximate: true
  },
  {
    id: "stagecoach-2026",
    title: "Stagecoach Country Music Festival",
    category: "Music",
    city: "Indio",
    state: "California",
    stateCode: "CA",
    date: "2026-04-24",
    endDate: "2026-04-26",
    description: "America's largest country music festival held on the same Coachella Valley grounds as its sister festival, featuring the biggest names in country and Americana over three sun-soaked desert days.",
    tags: ["country", "music", "california", "desert", "americana"],
    ticketUrl: "https://stagecoachfestival.com",
    featured: false,
    image: "",
    price: "$350–$900",
    organizer: "Goldenvoice",
    vendorOpportunities: true,
    emoji: "🤠",
    datesApproximate: true
  },
  {
    id: "hardly-strictly-bluegrass-2026",
    title: "Hardly Strictly Bluegrass",
    category: "Music",
    city: "San Francisco",
    state: "California",
    stateCode: "CA",
    date: "2026-10-02",
    endDate: "2026-10-04",
    description: "San Francisco's beloved free three-day music festival in Golden Gate Park celebrating bluegrass, folk, country, and Americana with world-class artists — always completely free to attend.",
    tags: ["bluegrass", "folk", "free", "california", "san francisco", "country"],
    ticketUrl: "https://hardlystrictlybluegrass.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Hardly Strictly Bluegrass",
    vendorOpportunities: false,
    emoji: "🪕",
    datesApproximate: true
  },
  {
    id: "bumbershoot-2026",
    title: "Bumbershoot",
    category: "Music",
    city: "Seattle",
    state: "Washington",
    stateCode: "WA",
    date: "2026-09-05",
    endDate: "2026-09-06",
    description: "Seattle's iconic Labor Day weekend arts and music festival at Seattle Center, blending indie music, visual art, comedy, dance, and literary events in a signature Pacific Northwest atmosphere.",
    tags: ["music", "art", "washington", "seattle", "indie", "comedy"],
    ticketUrl: "https://bumbershoot.com",
    featured: false,
    image: "",
    price: "$90–$200",
    organizer: "Bumbershoot",
    vendorOpportunities: true,
    emoji: "☔",
    datesApproximate: true
  },
  {
    id: "portland-night-market-2026",
    title: "Portland Night Market",
    category: "Food",
    city: "Portland",
    state: "Oregon",
    stateCode: "OR",
    date: "2026-08-07",
    endDate: "2026-08-09",
    description: "Portland's vibrant night bazaar inspired by Asian night markets, featuring local and international street food, artisan vendors, live music, and immersive outdoor ambiance.",
    tags: ["food", "free", "oregon", "portland", "street food", "artisan"],
    ticketUrl: "https://portlandnightmarket.com",
    featured: false,
    image: "",
    price: "Free (entry)",
    organizer: "Portland Night Market",
    vendorOpportunities: true,
    emoji: "🍜",
    datesApproximate: true
  },
  {
    id: "albuquerque-balloon-fiesta-2026",
    title: "Albuquerque International Balloon Fiesta",
    category: "Cultural",
    city: "Albuquerque",
    state: "New Mexico",
    stateCode: "NM",
    date: "2026-10-03",
    endDate: "2026-10-11",
    description: "The world's largest hot air balloon event filling New Mexico's famous blue skies with 500+ balloons during the mass ascensions, special shapes rodeos, and glow events at Balloon Fiesta Park.",
    tags: ["cultural", "new mexico", "balloon", "family", "outdoor"],
    ticketUrl: "https://balloonfiesta.com",
    featured: false,
    image: "",
    price: "$15–$30",
    organizer: "Albuquerque International Balloon Fiesta",
    vendorOpportunities: true,
    emoji: "🎈",
    datesApproximate: true
  },
  {
    id: "san-antonio-fiesta-2026",
    title: "Fiesta San Antonio",
    category: "Cultural",
    city: "San Antonio",
    state: "Texas",
    stateCode: "TX",
    date: "2026-04-16",
    endDate: "2026-04-26",
    description: "San Antonio's 11-day citywide celebration honoring Texas heroes with 100+ events including parades, outdoor fairs, night festivities, and culinary celebrations drawing over 3.5 million visitors.",
    tags: ["cultural", "texas", "san antonio", "parade", "family", "food"],
    ticketUrl: "https://fiesta-sa.org",
    featured: false,
    image: "",
    price: "Varies by event",
    organizer: "Fiesta San Antonio Commission",
    vendorOpportunities: true,
    emoji: "🎉",
    datesApproximate: true
  },
  {
    id: "artscape-baltimore-2026",
    title: "Artscape",
    category: "Art",
    city: "Baltimore",
    state: "Maryland",
    stateCode: "MD",
    date: "2026-07-17",
    endDate: "2026-07-19",
    description: "America's largest free arts festival transforms Baltimore's Station North Arts District into a massive outdoor gallery with 150+ visual artists, multiple music stages, and live performances.",
    tags: ["art", "free", "maryland", "baltimore", "music", "outdoor"],
    ticketUrl: "https://artscape.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Baltimore Office of Promotion & The Arts",
    vendorOpportunities: true,
    emoji: "🎨",
    datesApproximate: true
  },
  {
    id: "charlotte-shout-2026",
    title: "Charlotte SHOUT!",
    category: "Cultural",
    city: "Charlotte",
    state: "North Carolina",
    stateCode: "NC",
    date: "2026-10-09",
    endDate: "2026-10-18",
    description: "Charlotte's bold 10-day arts festival transforming uptown with immersive public art installations, live performances, food experiences, and community celebrations across the city.",
    tags: ["cultural", "art", "north carolina", "charlotte", "music", "community"],
    ticketUrl: "https://charlotteshout.com",
    featured: false,
    image: "",
    price: "Free & ticketed events",
    organizer: "Charlotte Center City Partners",
    vendorOpportunities: true,
    emoji: "🎭",
    datesApproximate: true
  },
  {
    id: "summerfest-2026",
    title: "Summerfest",
    category: "Music",
    city: "Milwaukee",
    state: "Wisconsin",
    stateCode: "WI",
    date: "2026-06-25",
    endDate: "2026-07-05",
    description: "The world's largest music festival on the shore of Lake Michigan in Milwaukee — 11 days, 1,000+ acts on 12 stages spanning every genre imaginable, from country to metal to hip-hop.",
    tags: ["music", "multi-genre", "wisconsin", "milwaukee", "lakefront"],
    ticketUrl: "https://summerfest.com",
    featured: false,
    image: "",
    price: "$30–$125",
    organizer: "Milwaukee World Festival, Inc.",
    vendorOpportunities: true,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "minneapolis-aquatennial-2026",
    title: "Minneapolis Aquatennial",
    category: "Cultural",
    city: "Minneapolis",
    state: "Minnesota",
    stateCode: "MN",
    date: "2026-07-16",
    endDate: "2026-07-25",
    description: "Minneapolis's official 10-day summer celebration featuring milk carton boat races, beach volleyball, sand sculpture competition, torchlight parade, and waterworks fireworks over the Mississippi River.",
    tags: ["cultural", "free", "minnesota", "minneapolis", "outdoor", "family"],
    ticketUrl: "https://aquatennial.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Minneapolis Jaycees",
    vendorOpportunities: true,
    emoji: "🚤",
    datesApproximate: true
  },
  {
    id: "three-rivers-arts-festival-2026",
    title: "Three Rivers Arts Festival",
    category: "Art",
    city: "Pittsburgh",
    state: "Pennsylvania",
    stateCode: "PA",
    date: "2026-06-05",
    endDate: "2026-06-14",
    description: "Pittsburgh's landmark 10-day arts festival with over 200 juried artists, multiple music stages with free concerts, interactive art, film screenings, and performances in the Cultural District.",
    tags: ["art", "free", "pennsylvania", "pittsburgh", "music", "juried"],
    ticketUrl: "https://traf.trustarts.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Pittsburgh Cultural Trust",
    vendorOpportunities: false,
    emoji: "🎨",
    datesApproximate: true
  },
  {
    id: "international-festival-arts-ideas-2026",
    title: "International Festival of Arts & Ideas",
    category: "Art",
    city: "New Haven",
    state: "Connecticut",
    stateCode: "CT",
    date: "2026-06-12",
    endDate: "2026-06-28",
    description: "A two-week free international festival of performing arts and ideas at Yale University's city, drawing world-renowned artists and thinkers for 100+ events in New Haven's historic downtown.",
    tags: ["art", "free", "connecticut", "new haven", "performance", "ideas"],
    ticketUrl: "https://artidea.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "International Festival of Arts & Ideas",
    vendorOpportunities: false,
    emoji: "💡",
    datesApproximate: true
  },
  {
    id: "mountain-dance-folk-festival-2026",
    title: "Mountain Dance and Folk Festival",
    category: "Music",
    city: "Asheville",
    state: "North Carolina",
    stateCode: "NC",
    date: "2026-08-06",
    endDate: "2026-08-08",
    description: "The nation's oldest folk festival, founded in 1928 and held in Asheville's Diana Wortham Theatre, celebrating Appalachian mountain music, flatfoot dancing, and clogging with master traditional artists.",
    tags: ["folk", "music", "free", "north carolina", "asheville", "appalachian", "dance"],
    ticketUrl: "https://folkheritage.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Southern Appalachian Repertory Theatre",
    vendorOpportunities: false,
    emoji: "🪕",
    datesApproximate: true
  },
  {
    id: "houston-livestock-rodeo-2026",
    title: "Houston Livestock Show and Rodeo",
    category: "Cultural",
    city: "Houston",
    state: "Texas",
    stateCode: "TX",
    date: "2026-02-28",
    endDate: "2026-03-22",
    description: "The world's largest rodeo and livestock show at NRG Stadium, featuring champion rodeo events, A-list concert entertainment, carnival, and BBQ competitions drawing 2.5 million visitors over three weeks.",
    tags: ["rodeo", "cultural", "texas", "houston", "country", "family"],
    ticketUrl: "https://rodeohouston.com",
    featured: false,
    image: "",
    price: "$15–$100",
    organizer: "Houston Livestock Show and Rodeo",
    vendorOpportunities: true,
    emoji: "🤠",
    datesApproximate: true
  },
  {
    id: "nashville-hot-chicken-festival-2026",
    title: "Nashville Hot Chicken Festival",
    category: "Food",
    city: "Nashville",
    state: "Tennessee",
    stateCode: "TN",
    date: "2026-07-04",
    endDate: "2026-07-04",
    description: "Nashville's free Fourth of July celebration of its most iconic dish, with local and national hot chicken vendors competing for the title of best hot chicken at East Park.",
    tags: ["food", "free", "tennessee", "nashville", "july 4th", "hot chicken"],
    ticketUrl: "https://nashvillehotchickenfestival.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Nashville Hot Chicken Festival",
    vendorOpportunities: true,
    emoji: "🍗",
    datesApproximate: true
  },
  {
    id: "austin-city-limits-2026",
    title: "Austin City Limits Music Festival",
    category: "Music",
    city: "Austin",
    state: "Texas",
    stateCode: "TX",
    date: "2026-10-02",
    endDate: "2026-10-11",
    description: "Austin's legendary two-weekend music festival in Zilker Park featuring 130+ artists across 8 stages with a mix of indie, rock, pop, hip-hop, electronic, and country acts.",
    tags: ["music", "featured", "texas", "austin", "indie", "rock", "two weekends"],
    ticketUrl: "https://aclfestival.com",
    featured: true,
    image: "",
    price: "$250–$400",
    organizer: "C3 Presents",
    vendorOpportunities: true,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "mobile-mardi-gras-2026",
    title: "Mobile Mardi Gras",
    category: "Cultural",
    city: "Mobile",
    state: "Alabama",
    stateCode: "AL",
    date: "2026-02-21",
    endDate: "2026-03-03",
    description: "America's original Mardi Gras — Mobile's celebration predates New Orleans by years, featuring Joe Cain Day, 40+ parades, mystic society balls, and the beloved traditions of the Gulf Coast Carnival.",
    tags: ["cultural", "free", "alabama", "mardi gras", "parade", "cajun"],
    ticketUrl: "https://mobilemardgras.com",
    featured: false,
    image: "",
    price: "Free (street)",
    organizer: "Mobile Carnival Association",
    vendorOpportunities: true,
    emoji: "🎭",
    datesApproximate: true
  },
  {
    id: "savannah-music-festival-2026",
    title: "Savannah Music Festival",
    category: "Music",
    city: "Savannah",
    state: "Georgia",
    stateCode: "GA",
    date: "2026-03-27",
    endDate: "2026-04-12",
    description: "One of America's finest music festivals bringing 100+ performances spanning jazz, classical, roots, bluegrass, and world music to Savannah's historic theaters and outdoor squares.",
    tags: ["music", "jazz", "classical", "georgia", "savannah", "multi-genre"],
    ticketUrl: "https://savannahmusicfestival.org",
    featured: false,
    image: "",
    price: "$20–$75",
    organizer: "Savannah Music Festival",
    vendorOpportunities: false,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "telluride-bluegrass-festival-2026",
    title: "Telluride Bluegrass Festival",
    category: "Music",
    city: "Telluride",
    state: "Colorado",
    stateCode: "CO",
    date: "2026-06-18",
    endDate: "2026-06-21",
    description: "The world's most beautiful bluegrass festival nestled in a Colorado mountain box canyon at 9,000 feet, drawing top bluegrass and Americana artists to a stunning natural amphitheater.",
    tags: ["bluegrass", "music", "colorado", "mountain", "americana", "camping"],
    ticketUrl: "https://bluegrass.com",
    featured: false,
    image: "",
    price: "$100–$350",
    organizer: "Planet Bluegrass",
    vendorOpportunities: true,
    emoji: "🏔️",
    datesApproximate: true
  },
  {
    id: "newport-folk-festival-2026",
    title: "Newport Folk Festival",
    category: "Music",
    city: "Newport",
    state: "Rhode Island",
    stateCode: "RI",
    date: "2026-07-31",
    endDate: "2026-08-02",
    description: "One of America's most historic music festivals at Fort Adams State Park — where Bob Dylan plugged in — celebrating folk, Americana, and roots music with legendary surprise collaborations.",
    tags: ["folk", "music", "rhode island", "newport", "americana", "historic"],
    ticketUrl: "https://newportfolk.org",
    featured: false,
    image: "",
    price: "$80–$200",
    organizer: "Newport Festivals Foundation",
    vendorOpportunities: false,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "vermont-brewers-festival-2026",
    title: "Vermont Brewers Festival",
    category: "Food",
    city: "Burlington",
    state: "Vermont",
    stateCode: "VT",
    date: "2026-07-17",
    endDate: "2026-07-18",
    description: "New England's premier craft beer festival on the Burlington waterfront featuring 50+ Vermont craft breweries pouring 200+ beers alongside live music and local food vendors.",
    tags: ["food", "beer", "vermont", "burlington", "craft", "music"],
    ticketUrl: "https://vtbrewfest.com",
    featured: false,
    image: "",
    price: "$45–$65",
    organizer: "Vermont Brewers Association",
    vendorOpportunities: true,
    emoji: "🍺",
    datesApproximate: true
  },
  {
    id: "all-souls-procession-2026",
    title: "All Souls Procession",
    category: "Cultural",
    city: "Tucson",
    state: "Arizona",
    stateCode: "AZ",
    date: "2026-11-01",
    endDate: "2026-11-01",
    description: "Tucson's stunning community art event honoring the dead — tens of thousands march through downtown in elaborate costumes and face paint in one of America's most moving free cultural celebrations.",
    tags: ["cultural", "free", "arizona", "tucson", "dia de los muertos", "parade"],
    ticketUrl: "https://allsoulsprocession.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Many Mouths One Stomach",
    vendorOpportunities: true,
    emoji: "💀",
    datesApproximate: true
  },
  {
    id: "old-port-festival-portland-me-2026",
    title: "Old Port Festival",
    category: "Cultural",
    city: "Portland",
    state: "Maine",
    stateCode: "ME",
    date: "2026-06-07",
    endDate: "2026-06-07",
    description: "Portland Maine's beloved summer kickoff festival transforming the cobblestone Old Port district with live music on multiple stages, local artisan vendors, seafood, and family fun.",
    tags: ["cultural", "free", "maine", "portland", "seafood", "music"],
    ticketUrl: "https://portlandmaine.com",
    featured: false,
    image: "",
    price: "Free",
    organizer: "Portland Downtown District",
    vendorOpportunities: true,
    emoji: "⚓",
    datesApproximate: true
  },
  {
    id: "chicago-blues-festival-2026",
    title: "Chicago Blues Festival",
    category: "Music",
    city: "Chicago",
    state: "Illinois",
    stateCode: "IL",
    date: "2026-06-12",
    endDate: "2026-06-14",
    description: "The world's largest free blues festival in Millennium Park and Grant Park, celebrating Chicago's unparalleled blues legacy with legendary artists and emerging voices on six outdoor stages.",
    tags: ["blues", "music", "free", "illinois", "chicago", "outdoor"],
    ticketUrl: "https://cityofchicago.org",
    featured: false,
    image: "",
    price: "Free",
    organizer: "City of Chicago",
    vendorOpportunities: true,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "gasparilla-music-festival-2026",
    title: "Gasparilla Music Festival",
    category: "Music",
    city: "Tampa",
    state: "Florida",
    stateCode: "FL",
    date: "2026-03-27",
    endDate: "2026-03-28",
    description: "Tampa's premier indie and alternative music festival in Gasparilla's spirit, featuring national touring acts across multiple stages in Curtis Hixon Waterfront Park.",
    tags: ["music", "indie", "florida", "tampa", "waterfront", "alternative"],
    ticketUrl: "https://gasparillamusicfestival.com",
    featured: false,
    image: "",
    price: "$60–$140",
    organizer: "Gasparilla Music Foundation",
    vendorOpportunities: true,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "kc-jazz-heritage-festival-2026",
    title: "Kansas City Jazz & Heritage Festival",
    category: "Music",
    city: "Kansas City",
    state: "Missouri",
    stateCode: "MO",
    date: "2026-07-24",
    endDate: "2026-07-26",
    description: "A celebration of Kansas City's legendary jazz tradition on the historic 18th & Vine Jazz District, featuring world-class jazz, blues, and R&B performers across multiple outdoor stages.",
    tags: ["jazz", "blues", "music", "missouri", "kansas city", "heritage"],
    ticketUrl: "https://kcjazzheritage.org",
    featured: false,
    image: "",
    price: "$20–$60",
    organizer: "KC Jazz Heritage Foundation",
    vendorOpportunities: true,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "cincinnati-music-festival-2026",
    title: "Cincinnati Music Festival",
    category: "Music",
    city: "Cincinnati",
    state: "Ohio",
    stateCode: "OH",
    date: "2026-07-23",
    endDate: "2026-07-26",
    description: "One of the nation's largest urban music events and Black cultural gatherings, bringing the biggest names in R&B and soul music to Paycor Stadium over four nights in Cincinnati.",
    tags: ["r&b", "soul", "music", "ohio", "cincinnati", "urban"],
    ticketUrl: "https://cincinnatimusic.com",
    featured: false,
    image: "",
    price: "$100–$300",
    organizer: "Cincinnati Music Festival",
    vendorOpportunities: false,
    emoji: "🎤",
    datesApproximate: true
  },
  {
    id: "san-diego-jazz-festival-2026",
    title: "San Diego Jazz Festival",
    category: "Music",
    city: "San Diego",
    state: "California",
    stateCode: "CA",
    date: "2026-11-26",
    endDate: "2026-11-29",
    description: "A beloved Thanksgiving weekend tradition in San Diego, bringing together traditional jazz, swing, and Dixieland musicians from around the world for four days of joyful performances.",
    tags: ["jazz", "dixieland", "music", "california", "san diego", "thanksgiving"],
    ticketUrl: "https://sandiegojazz.org",
    featured: false,
    image: "",
    price: "$25–$80",
    organizer: "San Diego Traditional Jazz Society",
    vendorOpportunities: false,
    emoji: "🎷",
    datesApproximate: true
  },
  {
    id: "primavera-sound-la-2026",
    title: "Primavera Sound Los Angeles",
    category: "Music",
    city: "Los Angeles",
    state: "California",
    stateCode: "CA",
    date: "2026-09-18",
    endDate: "2026-09-20",
    description: "The acclaimed Barcelona festival's LA edition at the Rose Bowl, bringing Primavera's signature curation of indie, electronic, and alternative acts to Southern California.",
    tags: ["music", "indie", "electronic", "california", "los angeles", "alternative"],
    ticketUrl: "https://primaverasound.com",
    featured: false,
    image: "",
    price: "$175–$400",
    organizer: "Primavera Sound",
    vendorOpportunities: false,
    emoji: "🎵",
    datesApproximate: true
  },
  {
    id: "sedona-film-festival-2026",
    title: "Sedona International Film Festival",
    category: "Art",
    city: "Sedona",
    state: "Arizona",
    stateCode: "AZ",
    date: "2026-02-20",
    endDate: "2026-03-01",
    description: "One of the Southwest's most respected film festivals set against Sedona's iconic red rocks, screening 170+ films from 40+ countries alongside filmmaker panels and starry special events.",
    tags: ["film", "art", "arizona", "sedona", "international", "cinema"],
    ticketUrl: "https://sedonafilmfestival.com",
    featured: false,
    image: "",
    price: "$15–$50",
    organizer: "Sedona International Film Festival",
    vendorOpportunities: false,
    emoji: "🎬",
    datesApproximate: true
  },
  {
    id: "mardi-gras-galveston-2026",
    title: "Mardi Gras Galveston",
    category: "Cultural",
    city: "Galveston",
    state: "Texas",
    stateCode: "TX",
    date: "2026-02-14",
    endDate: "2026-02-22",
    description: "Texas's biggest Mardi Gras celebration on Galveston Island, with elaborate parades on the historic Strand, live music stages, costume contests, and the authentic Gulf Coast spirit of Carnival.",
    tags: ["cultural", "texas", "galveston", "mardi gras", "parade", "music"],
    ticketUrl: "https://mardigrasgalveston.com",
    featured: false,
    image: "",
    price: "Free (street)",
    organizer: "Mardi Gras Galveston",
    vendorOpportunities: true,
    emoji: "🎭",
    datesApproximate: true
  },
  {
    id: "underground-music-showcase-2026",
    title: "Underground Music Showcase",
    category: "Music",
    city: "Denver",
    state: "Colorado",
    stateCode: "CO",
    date: "2026-07-23",
    endDate: "2026-07-26",
    description: "Denver's beloved indie music festival taking over South Broadway with 400+ local and national acts across 30+ venues — a true community-driven celebration of independent music culture.",
    tags: ["indie", "music", "multi-venue", "colorado", "denver", "alternative"],
    ticketUrl: "https://undergroundmusicshowcase.com",
    featured: false,
    image: "",
    price: "$50–$90",
    organizer: "Underground Music Showcase",
    vendorOpportunities: false,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "capitol-hill-block-party-2026",
    title: "Capitol Hill Block Party",
    category: "Music",
    city: "Seattle",
    state: "Washington",
    stateCode: "WA",
    date: "2026-07-24",
    endDate: "2026-07-26",
    description: "Seattle's indie and alternative music institution on the legendary Capitol Hill neighborhood streets, featuring curated lineups of indie, electronic, and alternative artists over three days.",
    tags: ["indie", "music", "washington", "seattle", "alternative", "outdoor"],
    ticketUrl: "https://capitolhillblockparty.com",
    featured: false,
    image: "",
    price: "$90–$175",
    organizer: "Capitol Hill Block Party",
    vendorOpportunities: false,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "shaky-knees-festival-2026",
    title: "Shaky Knees Music Festival",
    category: "Music",
    city: "Atlanta",
    state: "Georgia",
    stateCode: "GA",
    date: "2026-05-01",
    endDate: "2026-05-03",
    description: "Atlanta's premier rock and indie festival at Central Park, featuring three days of rock royalty and rising stars across multiple stages in the heart of Midtown Atlanta.",
    tags: ["rock", "indie", "music", "georgia", "atlanta", "alternative"],
    ticketUrl: "https://shakykneesfestival.com",
    featured: false,
    image: "",
    price: "$150–$300",
    organizer: "Shaky Boots Promotions",
    vendorOpportunities: true,
    emoji: "🎸",
    datesApproximate: true
  },
  {
    id: "portland-jazz-festival-2026",
    title: "Portland Jazz Festival",
    category: "Music",
    city: "Portland",
    state: "Oregon",
    stateCode: "OR",
    date: "2026-02-20",
    endDate: "2026-03-01",
    description: "The Pacific Northwest's premier jazz celebration bringing international jazz luminaries and cutting-edge young artists to Portland's theaters, clubs, and public spaces for 10 days of free and ticketed events.",
    tags: ["jazz", "music", "oregon", "portland", "international", "multi-venue"],
    ticketUrl: "https://portlandjazz.com",
    featured: false,
    image: "",
    price: "Free & ticketed",
    organizer: "Portland Jazz Festival",
    vendorOpportunities: false,
    emoji: "🎷",
    datesApproximate: true
  }

];

// Utility: get all unique cities
window.FESTIVAL_CITIES = [...new Set(window.FESTIVALS_DATA.map(f => f.city))].sort();

// Utility: get all unique states
window.FESTIVAL_STATES = [...new Set(window.FESTIVALS_DATA.map(f => f.state))].sort();
